-- MySQL Script generated by MySQL Workbench
-- Thu Oct 24 11:02:13 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_barang
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_barang
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_barang` DEFAULT CHARACTER SET utf8 ;
USE `db_barang` ;

-- -----------------------------------------------------
-- Table `db_barang`.`dataBarang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_barang`.`dataBarang` (
  `id_barang` VARCHAR(45) NOT NULL,
  `merk_barang` VARCHAR(45) NOT NULL,
  `tipe_barang` VARCHAR(45) NOT NULL,
  `tahun_produksi_barang` INT NOT NULL,
  `harga_barang` DOUBLE NOT NULL,
  `stok_barang` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_barang`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_barang`.`kasirTransaksi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_barang`.`kasirTransaksi` (
  `merk_barang` VARCHAR(45) NOT NULL,
  `tipe_barang` VARCHAR(45) NOT NULL,
  `tahun_produksi_barang` INT NOT NULL,
  `harga_barang` DOUBLE NOT NULL,
  `harga_total` DOUBLE NOT NULL,
  `id_transaksi` VARCHAR(45) NOT NULL,
  `kuantitas` INT NOT NULL,
  `waktu_transaksi` DATE NOT NULL,
  `nama_pegawal_kasir` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_transaksi`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_barang`.`histori_transaksi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_barang`.`histori_transaksi` (
  `merk_barang` VARCHAR(45) NOT NULL,
  `tipe_barang` VARCHAR(45) NOT NULL,
  `tahun_produksi_barang` INT NOT NULL,
  `harga_barang` DOUBLE NOT NULL,
  `harga_total` DOUBLE NOT NULL,
  `id_histori_transaksi` VARCHAR(45) NOT NULL,
  `kuantitas` INT NOT NULL,
  `waktu_transaksi` DATE NOT NULL,
  `nama_pegawal_kasir` VARCHAR(45) NOT NULL,
  `nominal_bayar` DOUBLE NOT NULL,
  `nominal_kembalian` DOUBLE NOT NULL,
  PRIMARY KEY (`id_histori_transaksi`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
